Repository fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY, pull requests merged in 2022-10, with the labels that each got.

#13 Create fibonacci.py
  recursion/fibonacci.py
Labels: hacktoberfest

#18 Added Recursion Basic Questions
  recursion/Basic Questions/Factorial.py
  recursion/Basic Questions/Multiplication_Of_Two_Numbers.py
  recursion/Basic Questions/Multiplication_Table.py
  recursion/Basic Questions/Power_Linear.py
  recursion/Basic Questions/Power_Logarithmic.py
  recursion/Basic Questions/Print_Decreasing.py
  recursion/Basic Questions/Print_Increasing.py
  recursion/Basic Questions/Print_Increasing_Decreasing.py
  recursion/Basic Questions/Tower_Of_Hanoi.py
  recursion/Basic Questions/Zig_Zag.py
Labels: hacktoberfest

#9 Added quick sort py
  Searching & sorting/Quicksort Python One-liner.py
Labels: hacktoberfest

#11 Added Insertion and Merge Sort
  Searching & sorting/Searching/linear_search.py
  Searching & sorting/Sorting/Insertion Sort.py
  Searching & sorting/Sorting/Merge Sort.py
Labels: hacktoberfest-accepted

#47 Update DuplicateElement.py
  function and array/DuplicateElement.py
Labels: hacktoberfest-accepted

#45 Update Recursive_factorial_fun.py
  recursion/Recursive_factorial_fun.py
Labels: hacktoberfest-accepted

#44 Number pattern programs
  pattern/pattern-6.py
  pattern/pattern-7.py
  pattern/pattern-8.py
Labels: hacktoberfest-accepted

#56 Created pigeonholesort
  Searching & sorting/Sorting/Pigeonholesort.py
Labels: hacktoberfest-accepted

#66 Added Radixsort
  Searching & sorting/Sorting/Radixsort.py
Labels: hacktoberfest, hacktoberfest-accepted

#73 Creating Interpolation Search
  Searching & sorting/Searching/Interpolation_Search.py
Labels: hacktoberfest-accepted, unique

#82 Added JumpSearch
  Searching & sorting/Searching/Jumpsearch.py
Labels: hacktoberfest, unique

#85 Added recursion basic maths questions
  recursion/Basic Questions/Count_Zeros.py
  recursion/Basic Questions/Geometric_Sum.py
  recursion/Basic Questions/Sum_Of_Digit.py
Labels: hacktoberfest

#93 Radix sort
  Searching & sorting/radix sort.py
Labels: hacktoberfest-accepted

#102 Created Longest Palindromic Substring
  String/longestPalindromicSubstring.py
Labels: hacktoberfest-accepted

#111 Created First Repeated word in a string
  String/firstReapeatedWord.py
Labels: hacktoberfest-accepted

#113 Created Number of palindromic Substrings
  String/numberOfPalindromicSubstrings.py
Labels: hacktoberfest-accepted

#164 Created Shortest path in binary maze
  2dmatrix/Shortestpath.py
Labels: hacktoberfest, hacktoberfest-accepted

#163 Created Number of islands
  2dmatrix/Noofislands.py
Labels: hacktoberfest, hacktoberfest-accepted

#156 Added sudoko
  2dmatrix/Sudoko.py
Labels: hacktoberfest, hacktoberfest-accepted

#150 created partitioning
  String/partitioning_string.py
Labels: hacktoberfest, hacktoberfest-accepted

#146 created password_checker.py
  String/password_checker.py
Labels: hacktoberfest, hacktoberfest-accepted

#147 BINARY SEARCH FOR UNSORTED ARRAYS
  Searching & sorting/Searching/binary_unsorted.py
Labels: hacktoberfest, hacktoberfest-accepted, unique

#167 Recursive Seection Sort
  Searching & sorting/Sorting/Recursive Selection Sort.py
Labels: hacktoberfest-accepted

#177 created dearrangements
  Derangements.py
Labels: hacktoberfest, hacktoberfest-accepted

#175 Create 3sum.py
  Arrays/3sum.py
Labels: hacktoberfest, hacktoberfest-accepted

#179 Created dearrangement
  Arrays/dearrangement.py
Labels: hacktoberfest, hacktoberfest-accepted

#182 created recursivebubblesort
  recursivebubblesort.py
Labels: hacktoberfest, hacktoberfest-accepted, unique

#189 created uniquepaths.py
  questions/uniquepaths.py
Labels: hacktoberfest, hacktoberfest-accepted

#186 Adding Bucket Sort to 'Sorting and Searching' Folder after final checks
  Searching & sorting/Sorting/BucketSort.py
Labels: hacktoberfest, hacktoberfest-accepted

#194 created palindromesubstring
  recursion/palindromesubstring.py
Labels: hacktoberfest, hacktoberfest-accepted

#215 Created minJumpsDP.py
  Arrays/unionIntersection.py
Labels: hacktoberfest, hacktoberfest-accepted

#214 Created a new file trappingRainWater.py
  Arrays/trapRainWater.py
Labels: hacktoberfest, hacktoberfest-accepted

#213 Created new file evenoddarr.py
  questions/evenoddarr.py
Labels: hacktoberfest, hacktoberfest-accepted

#212 Created sort012.py
  Arrays/sort012.py
Labels: hacktoberfest, hacktoberfest-accepted
